# Base image
FROM node:22-alpine AS base

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy Prisma schema before generating
# COPY src/prisma ./src/prisma/

# Copy the rest of your application (optional, as we will mount it in dev)
COPY . .

# Generate Prisma Client
# RUN npx prisma generate --schema=./src/prisma/schema.prisma

# Build the application and then start it (for prod)
CMD ["sh", "-c", "npm run dev"]  # Development commands

